name: ledger-system

services:
  postgres:
    image: postgres:16
    # image: pgvector/pgvector:pg16
    profiles: ["deps", "full"]
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ledgeruser
      POSTGRES_PASSWORD: ledgerpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./pg-init:/docker-entrypoint.initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgeruser -d ledgerdb"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  ledger:
    build:
      context: ./ledger
      dockerfile: Dockerfile
    profiles: ["full"]
    container_name: ledgerapp
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ledgerdb
      SPRING_DATASOURCE_USERNAME: ledgeruser
      SPRING_DATASOURCE_PASSWORD: ledgerpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  seeder:
    build:
      context: ./data-seeder
      dockerfile: Dockerfile
    # volumes:
    # - sidecar-data:/data
    profiles: ["full"]
    depends_on:
      postgres:
        condition: service_started
      ledger:
        condition: service_healthy
    environment:
      RUN_SEEDER: false
      PG_URL: postgres://ledgeruser:ledgerpass@postgres:5432/ledgerdb?sslmode=disable
      LEDGER_API_URL: http://ledger:8080/api
      # SQLITE_PATH: /data/mirror.db
    restart: "no"

volumes:
  postgres_data:
  sidecar-data:
