package internal

import (
	"context"
	"fmt"
	"math"
	"math/rand"
	"strings"
	"time"
)

type DataGenerator struct {
	WriteToDBDirect bool
	validCategories []string
	CleanDB         bool

	httpClient *HTTPClient
	pg         *PGDB

	rng        *rand.Rand
	dateRange  DateRange
	startDate  time.Time
	endDate    time.Time
	originIDs  []int64
}

func (d *DataGenerator) nextOriginId() int64 {
	if len(d.originIDs) == 0 {
		return d.rng.Int63()
	}
	idx := d.rng.Intn(len(d.originIDs))
	return d.originIDs[idx]
}

func getGenerator(hc *HTTPClient, config *SeedConfig, pg *PGDB) *DataGenerator {
	start, err := time.Parse("2006-01-02", config.Base.DateRange.Start)
	if err != nil {
		panic(fmt.Sprintf("invalid start date %q: %v", config.Base.DateRange.Start, err))
	}
	end, err := time.Parse("2006-01-02", config.Base.DateRange.End)
	if err != nil {
		panic(fmt.Sprintf("invalid end date %q: %v", config.Base.DateRange.End, err))
	}

	rng := rand.New(rand.NewSource(int64(config.Base.Seed)))

	// Create a pool of 20 randomly generated device/terminal IDs
	originIDs := make([]int64, 20)
	for i := 0; i < 20; i++ {
		originIDs[i] = rng.Int63()
	}

	return &DataGenerator{
		WriteToDBDirect: config.Base.WriteToDB,
		CleanDB:         config.Base.CleanDBIfNotEmpty,
		httpClient:      hc,
		validCategories: config.Categories,
		rng:             rng,
		dateRange:       config.Base.DateRange,
		startDate:       start,
		endDate:         end,
		pg:              pg,
		originIDs:       originIDs,
	}
}

func (d *DataGenerator) startSeeding(config *SeedConfig) error {
	// do initial config settings

	if d.CleanDB {
		err := d.pg.ClearDB(context.Background())
		if err != nil {
			return fmt.Errorf("error clearing db: %w", err)
		}
	}

	for _, profile := range config.Profiles {
		if err := d.seedProfileData(&profile); err != nil {
			return err
		}
	}
	return nil
}

// seedProfileData seeds all data for one profile definition.
// For each instance in profile.Count it creates: 1 user, N accounts, and all
// transactions generated by the rule set over the configured date range.
func (d *DataGenerator) seedProfileData(profile *ProfileEntry) error {
	count := profile.Count
	if count <= 0 {
		count = 1
	}

	for i := int32(0); i < count; i++ {
		instanceSuffix := fmt.Sprintf("%s_%d", profile.Name, i)

		// ── 1. Create user ───────────────────────────────────────────────────
		userResp, err := d.httpClient.CreateUser(&CreateUserRequest{
			Name:     fmt.Sprintf("Seed User %s", instanceSuffix),
			Email:    fmt.Sprintf("seed.%s@ledger.local", instanceSuffix),
			Password: "Seed@1234!",
		})
		if err != nil {
			return fmt.Errorf("profile %s[%d]: create user: %w", profile.Name, i, err)
		}
		userID := userResp.UserId

		// ── 2. Create accounts ───────────────────────────────────────────────
		// accNumByID maps the config account ID (e.g. "salary_checking") to the
		// account number string returned by the API.
		accNumByID := make(map[string]string, len(profile.Accounts))

		// accountBalances tracks the running ledger balance of each account so
		// that settle_account amounts can be computed at rule-fire time.
		// For credit accounts this is the outstanding debit balance (positive =
		// amount owed).
		accountBalances := make(map[string]int64, len(profile.Accounts))

		for _, acc := range profile.Accounts {
			accNum := d.accountNumberGenerator()
			// accNum = fmt.Sprintf("%s-%s-%d", instanceSuffix, acc.Id, userID)
			accResp, err := d.httpClient.CreateAccount(&CreateAccountRequest{
				AccountNumber: accNum,
				AccountType:   mapAccountType(acc.Type),
				UserID:        userID,
			})
			if err != nil {
				return fmt.Errorf("profile %s[%d]: create account %s: %w",
					profile.Name, i, acc.Id, err)
			}
			_ = accResp // AccountId returned but we track by accNum string
			accNumByID[acc.Id] = accNum
			accountBalances[acc.Id] = acc.OpeningBalance
		}

		// Create an external account to act as the counter-party for all external
		// transactions where no target account is specified.
		externalAccNum := d.accountNumberGenerator()
		// externalAccNum = fmt.Sprintf("%s-external-%d", instanceSuffix, userID)
		_, err = d.httpClient.CreateAccount(&CreateAccountRequest{
			AccountNumber: externalAccNum,
			AccountType:   Checking,
			UserID:        userID,
		})
		if err != nil {
			return fmt.Errorf("profile %s[%d]: create external account: %w",
				profile.Name, i, err)
		}
		accNumByID["external"] = externalAccNum

		// Build BNPL config lookup by account ID
		bnplByAcc := make(map[string]*BNPLCfg)
		for _, acc := range profile.Accounts {
			if acc.Bnpl != nil {
				bnplByAcc[acc.Id] = acc.Bnpl
			}
		}

		// ── 3. Generate & post transactions ─────────────────────────────────
		if err := d.generateTransactions(
			profile, accNumByID, accountBalances, bnplByAcc,
		); err != nil {
			return fmt.Errorf("profile %s[%d]: generate transactions: %w",
				profile.Name, i, err)
		}
	}

	return nil
}

// generateTransactions iterates over the date range and fires rules in the
// correct order and cadence.
func (d *DataGenerator) generateTransactions(
	profile *ProfileEntry,
	accNumByID map[string]string,
	balances map[string]int64,
	bnplByAcc map[string]*BNPLCfg,
) error {
	start := d.startDate
	end := d.endDate

	// Pending BNPL installments: list of (day, accountID, amount).
	type scheduledTxn struct {
		date      time.Time
		accountID string // config ID
		amount    int64
		category  string
		desc      string
	}
	var bnplSchedule []scheduledTxn

	// one_time_in_range rules may only fire once per rule.
	oneTimeFired := make([]bool, len(profile.Rules))

	// refund_shadow: collect transactions that may spawn a refund later.
	type pendingRefund struct {
		fireDate  time.Time
		accountID string
		amount    int64
		origDesc  string
		rule      *RuleEntry
	}
	var pendingRefunds []pendingRefund

	// Iterate month by month
	current := time.Date(start.Year(), start.Month(), 1, 0, 0, 0, 0, time.UTC)
	for !current.After(end) {
		monthStart := current
		nextMonth := current.AddDate(0, 1, 0)
		monthEnd := nextMonth.AddDate(0, 0, -1)
		if monthEnd.After(end) {
			monthEnd = end
		}

		// Collect all (date, rule-index) firings for this month, then sort by
		// date so reactive rules can see the correct balance.
		var firings []firingEntry

		for ri, rule := range profile.Rules {
			switch rule.Type {
			case "monthly_fixed_day":
				day := int(rule.Day)
				d_ := time.Date(monthStart.Year(), monthStart.Month(), day, 0, 0, 0, 0, time.UTC)
				if !d_.Before(monthStart) && !d_.After(monthEnd) {
					firings = append(firings, firingEntry{date: d_, ruleIdx: ri})
				}

			case "monthly_day_range":
				if rule.DayRange == nil {
					continue
				}
				maxDay := int(rule.DayRange.Max)
				if mDays := daysInMonth(monthStart); maxDay > mDays {
					maxDay = mDays
				}
				day := d.randInt(int(rule.DayRange.Min), maxDay)
				d_ := time.Date(monthStart.Year(), monthStart.Month(), day, 0, 0, 0, 0, time.UTC)
				if !d_.Before(monthStart) && !d_.After(monthEnd) {
					firings = append(firings, firingEntry{date: d_, ruleIdx: ri})
				}

			case "weekly":
				targetWD := parseWeekday(rule.Weekday)
				// Walk every week in the month
				d_ := firstWeekdayOnOrAfter(monthStart, targetWD)
				for !d_.After(monthEnd) {
					firings = append(firings, firingEntry{date: d_, ruleIdx: ri})
					d_ = d_.AddDate(0, 0, 7)
				}

			case "random_n_per_month":
				if rule.Frequency == nil || rule.DayRange == nil {
					continue
				}
				count := d.sampleFrequency(rule.Frequency.Mean, rule.Frequency.Variance)
				for k := 0; k < count; k++ {
					maxDay := int(rule.DayRange.Max)
					if mDays := daysInMonth(monthStart); maxDay > mDays {
						maxDay = mDays
					}
					day := d.randInt(int(rule.DayRange.Min), maxDay)
					d_ := time.Date(monthStart.Year(), monthStart.Month(), day, 0, 0, 0, 0, time.UTC)
					if !d_.Before(monthStart) && !d_.After(monthEnd) {
						firings = append(firings, firingEntry{date: d_, ruleIdx: ri})
					}
				}

			case "decay_pattern":
				if rule.Decay == nil {
					continue
				}
				dec := rule.Decay
				// peak: days 1..inflection, trough: inflection+1..31
				// we compute expected counts per window and sample accordingly
				peakDays := dec.InflectionDay
				troughDays := daysInMonth(monthStart) - peakDays
				peakCount := d.sampleFrequency(dec.PeakFrequency, 0)
				troughCount := d.sampleFrequency(dec.TroughFrequency, 0)
				// peak firings
				for k := 0; k < peakCount; k++ {
					day := d.randInt(1, peakDays)
					d_ := time.Date(monthStart.Year(), monthStart.Month(), day, 0, 0, 0, 0, time.UTC)
					if !d_.Before(monthStart) && !d_.After(monthEnd) {
						firings = append(firings, firingEntry{date: d_, ruleIdx: ri})
					}
				}
				// trough firings
				for k := 0; k < troughCount; k++ {
					day := d.randInt(dec.InflectionDay+1, dec.InflectionDay+troughDays)
					d_ := time.Date(monthStart.Year(), monthStart.Month(), day, 0, 0, 0, 0, time.UTC)
					if !d_.Before(monthStart) && !d_.After(monthEnd) {
						firings = append(firings, firingEntry{date: d_, ruleIdx: ri})
					}
				}

			case "one_time_in_range":
				if oneTimeFired[ri] {
					continue
				}
				prob := 1.0
				if rule.Probability != nil {
					prob = *rule.Probability
				}
				if d.rng.Float64() > prob {
					oneTimeFired[ri] = true // mark as "decided not to fire"
					continue
				}
				if rule.DayRange == nil {
					continue
				}
				// DayRange is offset in days from date_range.start
				offsetMin := int(rule.DayRange.Min)
				offsetMax := int(rule.DayRange.Max)
				offset := d.randInt(offsetMin, offsetMax)
				fireDate := start.AddDate(0, 0, offset)
				// Only schedule if the resolved date falls in this month
				if fireDate.Year() == monthStart.Year() && fireDate.Month() == monthStart.Month() {
					firings = append(firings, firingEntry{date: fireDate, ruleIdx: ri})
					oneTimeFired[ri] = true
				}

			case "reactive_pct", "refund_shadow":
				// These are driven by other firings; handled below.
				continue
			}
		}

		// Sort firings by date (stable sort preserves rule declaration order
		// for same-day firings, which matters for reactive rules).
		sortFirings(firings)

		// Fire each scheduled transaction
		for _, f := range firings {
			rule := &profile.Rules[f.ruleIdx]

			// Resolve amount
			amount, err := d.resolveAmount(&rule.Amount, balances)
			if err != nil {
				return fmt.Errorf("rule %q on %s: resolve amount: %w",
					rule.Description, f.date.Format("2006-01-02"), err)
			}
			if amount == 0 {
				continue // e.g. settle_account when balance is zero
			}

			// Determine account
			accID := rule.Account
			if accID == "" {
				accID = rule.FromAccount
			}
			accNum, ok := accNumByID[accID]
			if !ok {
				return fmt.Errorf("rule %q: unknown account id %q", rule.Description, accID)
			}

			// Determine source and destination account numbers
			var srcAccNum, destAccNum string
			if rule.ToAccount != "" {
				// Internal transfer
				srcAccNum = accNumByID[rule.FromAccount]
				destAccNum = accNumByID[rule.ToAccount]
			} else {
				// External transaction
				if rule.Direction == Credited {
					srcAccNum = accNumByID["external"]
					destAccNum = accNum
				} else {
					srcAccNum = accNum
					destAccNum = accNumByID["external"]
				}
			}

			txnReq := &CreateTxnRequest{
				SourceAccNum:      srcAccNum,
				DestinationAccNum: destAccNum,
				OriginId:          d.nextOriginId(),
				Amount:            int32(amount),
				Note:              rule.Description,
			}

			if _, err := d.httpClient.CreateTransaction(txnReq); err != nil {
				return fmt.Errorf("rule %q on %s: create transaction: %w",
					rule.Description, f.date.Format("2006-01-02"), err)
			}

			// Update balances
			d.applyBalance(balances, rule, amount)

			// Handle BNPL: if the account has bnpl config, schedule installments
			if bnpl, hasBnpl := bnplByAcc[accID]; hasBnpl {
				installAmt := amount / int64(bnpl.InstallmentCount)
				for inst := 1; inst <= bnpl.InstallmentCount; inst++ {
					instDate := time.Date(
						f.date.Year(), f.date.Month()+time.Month(inst),
						bnpl.InstallmentDay, 0, 0, 0, 0, time.UTC,
					)
					bnplSchedule = append(bnplSchedule, scheduledTxn{
						date:      instDate,
						accountID: accID,
						amount:    installAmt,
						category:  rule.Category,
						desc:      fmt.Sprintf("BNPL Installment %d/%d: %s", inst, bnpl.InstallmentCount, rule.Description),
					})
				}
			}

			// Fire reactive_pct rules triggered by this transaction
			for ri2, r2 := range profile.Rules {
				if r2.Type != "reactive_pct" {
					continue
				}
				if r2.TriggerAccount != accID {
					continue
				}
				if r2.TriggerCategory != rule.Category {
					continue
				}
				if r2.Amount.Pct == nil {
					continue
				}
				_ = ri2
				reactAmt := int64(math.Round(float64(amount) * (*r2.Amount.Pct) / 100.0))
				if reactAmt == 0 {
					continue
				}

				var reactSrcNum, reactDestNum string
				if r2.ToAccount != "" {
					// Internal transfer
					reactSrcNum = accNumByID[r2.FromAccount]
					reactDestNum = accNumByID[r2.ToAccount]
				} else {
					// External transaction
					reactAcc := r2.Account
					if reactAcc == "" {
						reactAcc = r2.FromAccount
					}
					reactAccNum := accNumByID[reactAcc]
					if r2.Direction == Credited {
						reactSrcNum = accNumByID["external"]
						reactDestNum = reactAccNum
					} else {
						reactSrcNum = reactAccNum
						reactDestNum = accNumByID["external"]
					}
				}

				reactReq := &CreateTxnRequest{
					SourceAccNum:      reactSrcNum,
					DestinationAccNum: reactDestNum,
					OriginId:          d.nextOriginId(),
					Amount:            int32(reactAmt),
					Note:              r2.Description,
				}
				if _, err := d.httpClient.CreateTransaction(reactReq); err != nil {
					return fmt.Errorf("reactive rule %q on %s: %w",
						r2.Description, f.date.Format("2006-01-02"), err)
				}
				d.applyBalance(balances, &r2, reactAmt)
			}

			// Collect potential refund_shadow targets
			for _, r2 := range profile.Rules {
				if r2.Type != "refund_shadow" {
					continue
				}
				if r2.SourceCategory != rule.Category {
					continue
				}
				srcAcc := rule.Account
				if srcAcc == "" {
					srcAcc = rule.FromAccount
				}
				if r2.SourceAccount != srcAcc {
					continue
				}
				if r2.RefundProbability == nil {
					continue
				}
				pendingRefunds = append(pendingRefunds, pendingRefund{
					// delay resolved when we drain the list
					fireDate:  f.date,
					accountID: srcAcc,
					amount:    amount,
					origDesc:  rule.Description,
					rule:      func(r RuleEntry) *RuleEntry { return &r }(r2),
				})
			}
		}

		// ── BNPL installments that fall in this month ────────────────────────
		remaining := bnplSchedule[:0]
		for _, s := range bnplSchedule {
			if s.date.Year() == monthStart.Year() && s.date.Month() == monthStart.Month() {
				accNum := accNumByID[s.accountID]
				req := &CreateTxnRequest{
					SourceAccNum:      accNum,
					DestinationAccNum: accNumByID["external"],
					OriginId:          d.nextOriginId(),
					Amount:            int32(s.amount),
					Note:              s.desc,
				}
				if _, err := d.httpClient.CreateTransaction(req); err != nil {
					return fmt.Errorf("bnpl installment on %s: %w", s.date.Format("2006-01-02"), err)
				}
				balances[s.accountID] += s.amount
			} else {
				remaining = append(remaining, s)
			}
		}
		bnplSchedule = remaining

		// ── Refund shadows ───────────────────────────────────────────────────
		remainingRefunds := pendingRefunds[:0]
		for _, pr := range pendingRefunds {
			r2 := pr.rule
			if r2.RefundDelayDays == nil {
				continue
			}
			delayMin := int(r2.RefundDelayDays.Range.Min)
			delayMax := int(r2.RefundDelayDays.Range.Max)
			delay := d.randInt(delayMin, delayMax)
			refundDate := pr.fireDate.AddDate(0, 0, delay)
			if refundDate.After(end) {
				continue // outside range, drop
			}
			if refundDate.After(monthEnd) {
				remainingRefunds = append(remainingRefunds, pr)
				continue
			}
			// Fire this month
			if d.rng.Float64() >= *r2.RefundProbability {
				continue // probability check failed
			}
			desc := strings.ReplaceAll(r2.Description, "{source_description}", pr.origDesc)
			accNum := accNumByID[pr.accountID]
			req := &CreateTxnRequest{
				SourceAccNum:      accNumByID["external"],
				DestinationAccNum: accNum,
				OriginId:          d.nextOriginId(),
				Amount:            int32(pr.amount),
				Note:              desc,
			}
			if _, err := d.httpClient.CreateTransaction(req); err != nil {
				return fmt.Errorf("refund_shadow on %s: %w", refundDate.Format("2006-01-02"), err)
			}
			// Refund is a credit — reduce balance
			balances[pr.accountID] -= pr.amount
		}
		pendingRefunds = remainingRefunds

		current = nextMonth
	}

	return nil
}
