FROM python:3.12-slim-bookworm as builder

WORKDIR /app

COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY ./app /app

EXPOSE 8080

CMD ["fastapi", "run", "app/main.py", "--port", "8080" ]