package com.example.ledger.enums;

public enum ErrorCode {

    USER_NOT_FOUND, USER_ALREADY_EXISTS, ACCOUNT_NOT_FOUND, ACCOUNT_ALREADY_EXISTS, TXN_NOT_FOUND, TXN_ALREADY_EXISTS, INVALID_REQUEST, FORBIDDEN, INTERNAL_ERROR, VALIDATION_ERROR
}
